services:
  pgadmin:
    image: dpage/pgadmin4
    networks:
      - pg-network
    environment:
      PGADMIN_DEFAULT_EMAIL: walcutt.0@gmail.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    secrets:
      - pgadmin_password
    volumes:
      - "./db_volumes/pgadmin:/var/lib/pgadmin"
  postgres:
    image: postgres
    restart: always
    networks:
      - pg-network
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: markovblr
      PGDATA: /var/lib/postgres/data 
    secrets:
      - postgres_password
    volumes: 
      - "./db_volumes/postgres:/var/lib/postgres/data/"

networks:
  pg-network:

secrets:
  pgadmin_password:
    file: secrets/pgadmin/pgadmin-password.txt
  postgres_password:
    file: secrets/postgres/postgres-password.txt